CREATE TABLE [dbo].[AUTHOR] (
    [Id]        INT          IDENTITY (1, 1) NOT NULL,
    [LastName]  VARCHAR (50) NOT NULL,
    [FirstName] VARCHAR (50) NOT NULL,
    [BookID] INT NOT NULL, 
    PRIMARY KEY CLUSTERED ([Id] ASC), 
    CONSTRAINT [FK_AUTHOR_BOOK] FOREIGN KEY ([BookID]) REFERENCES [BOOK]([ID])
);

